version: '3.9'

services:
  db:
    image: postgres:16
    container_name: baltaci_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: baltaci_kitchen
      POSTGRES_USER: baltaci_user
      POSTGRES_PASSWORD: baltaci_password
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: baltaci_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  db_data:
